client_class_name: 'BaseClient'
num_epochs: 5
batch_size: 16
local_learning_rate: 5e-3
optimiser: "sgd"
num_cpus: 10
num_gpus: 1
momentum: 0.9
weight_decay: 1e-4

lr_scheduler:
  lr_decay:
    name: constant
    gamma:  0.999