num_clients: 100
num_rounds: 100
seed: 42
session_name: local_epochs_influence
algorithm: fedavg
device: cuda

server_config:
  fraction_fit: 0.1
  fraction_evaluate: 1
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

hydra:
  run:
    dir: ../${session_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - client_config: fedavg
  - dataset: cifar10
  - model: cnn_net
  