num_clients: 3
num_rounds: 50
seed: 42
session_name: fully_local_3_clients

client_config:
  num_epochs: 4 
  batch_size: 32
  learning_rate: 0.01
  optimiser: "sgd"
  num_cpus: 10
  num_gpus: 1

device: 'cuda'
  
dataset:
  name : "uoft-cs/cifar10"
  num_classes: 10
  seed: 42
  num_clients: ${num_clients}
  partitioner:
    name: "variable_pathological"
    # alpha:  0.1
    # alpha_rich: 2
    # alpha_poor: 0.6
    num_classes_per_partition: [9, 3, 3]  # Example for three partitions
model:
  num_classes: 10
  personalisation_level: 1
  in_channels: 3

server_config:
  fraction_fit: 1.0
  fraction_evaluate: 0.5
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

hydra:
  run:
    dir: ../${session_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}