num_clients: 10
num_rounds: 4
seed: 42
session_name: test
algorithm: fedavg
device: cuda

server_config:
  fraction_fit: 0.1
  fraction_evaluate: 1
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

hydra:
  run:
    #dir: ../${session_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.num}
    dir: ../${session_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - dataset: cifar10
  - client_config: fedavg
  - model: cnn_net