num_clients: 2
num_rounds: 10
seed: 42
session_name: test_tanguy

client_config:
  num_epochs: 4 
  batch_size: 32
  learning_rate: 0.01
  optimiser: "sgd"
  num_cpus: 10
  num_gpus: 0

device: 'cpu'
  

dataset:
  name : "fashion_mnist"
  # split: sample
  num_classes: 10
  seed: 42
  num_clients: ${num_clients}
 # fraction: 0.83

model:
  num_classes: 10

server_config:
  fraction_fit: 1.0
  fraction_evaluate: 0.5
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

hydra:
  run:
    dir: ../${session_name}/${now:%H-%M-%S}

